name: Build and publish document
on: push

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Generate HTML/TXT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            $HOME/.local/share/gem
            .refcache
          key: webdav-push.mkd

      - name: Install packages
        run: >
          sudo apt-get install --no-install-recommends -y golang-go &&
          sudo gem install kramdown-rfc &&
          sudo pip3 install svgcheck xml2rfc --break-system-packages &&
          go install github.com/blampe/goat/cmd/goat@latest && echo ~/go/bin >> $GITHUB_PATH

      - name: Prepare output directory
        run: mkdir build

      - name: Kramdown to XML
        run: kramdown-rfc2629 webdav-push.mkd >build/draft-bitfire-webdav-push-00.xml

      - name: XML to HTML
        run: (cd build; xml2rfc --html draft-bitfire-webdav-push-00.xml)
      - name: XML to TXT
        run: (cd build; xml2rfc --text draft-bitfire-webdav-push-00.xml)

      - uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
